-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Vehicle" (
    "vin" TEXT NOT NULL PRIMARY KEY,
    "stockNumber" TEXT,
    "year" INTEGER NOT NULL,
    "make" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "trim" TEXT,
    "bodyStyle" TEXT,
    "color" TEXT,
    "interiorColor" TEXT,
    "odometer" INTEGER NOT NULL DEFAULT 0,
    "condition" TEXT DEFAULT 'Used',
    "titleStatus" TEXT DEFAULT 'Clean',
    "keyId" TEXT,
    "engine" TEXT,
    "engineSize" TEXT,
    "engineCylinders" INTEGER,
    "transmission" TEXT,
    "transmissionType" TEXT,
    "transmissionSpeeds" INTEGER,
    "driveTrain" TEXT,
    "fuelType" TEXT,
    "doors" INTEGER,
    "cityMpg" INTEGER,
    "highwayMpg" INTEGER,
    "interiorOemColor" TEXT,
    "exteriorOemColor" TEXT,
    "vehicleCaption" TEXT,
    "category" TEXT,
    "size" TEXT,
    "vehicleEquipment" TEXT,
    "windowStickerEquipment" TEXT,
    "location" TEXT,
    "salesPerson" TEXT,
    "guarantee" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "isCertified" BOOLEAN NOT NULL DEFAULT false,
    "isOneOwner" BOOLEAN NOT NULL DEFAULT false,
    "warrantyAvailable" BOOLEAN NOT NULL DEFAULT false,
    "financingAvailable" BOOLEAN NOT NULL DEFAULT false,
    "isSold" BOOLEAN NOT NULL DEFAULT false,
    "isNew" BOOLEAN NOT NULL DEFAULT false,
    "isAsIs" BOOLEAN NOT NULL DEFAULT false,
    "flagLowMiles" BOOLEAN NOT NULL DEFAULT false,
    "flagNonSmoker" BOOLEAN NOT NULL DEFAULT false,
    "flagFullService" BOOLEAN NOT NULL DEFAULT false,
    "flagMultiPoint" BOOLEAN NOT NULL DEFAULT false,
    "flagNeverWrecked" BOOLEAN NOT NULL DEFAULT false,
    "flagFullyEquipped" BOOLEAN NOT NULL DEFAULT false,
    "flagLuxury" BOOLEAN NOT NULL DEFAULT false,
    "flagPowerful" BOOLEAN NOT NULL DEFAULT false,
    "flagFuelEfficient" BOOLEAN NOT NULL DEFAULT false,
    "flagSporty" BOOLEAN NOT NULL DEFAULT false,
    "flagOffRoad" BOOLEAN NOT NULL DEFAULT false,
    "flagMechanicallyPerfect" BOOLEAN NOT NULL DEFAULT false,
    "flagPerfectExterior" BOOLEAN NOT NULL DEFAULT false,
    "flagPerfectInterior" BOOLEAN NOT NULL DEFAULT false,
    "flagCleanExterior" BOOLEAN NOT NULL DEFAULT false,
    "flagCleanInterior" BOOLEAN NOT NULL DEFAULT false,
    "flagBelowBlueBook" BOOLEAN NOT NULL DEFAULT false,
    "flagLowMonthly" BOOLEAN NOT NULL DEFAULT false,
    "flagBhph" BOOLEAN NOT NULL DEFAULT false,
    "flagGuaranteedFin" BOOLEAN NOT NULL DEFAULT false,
    "flagCarfaxReport" BOOLEAN NOT NULL DEFAULT false,
    "flagCarfaxCertified" BOOLEAN NOT NULL DEFAULT false,
    "flagCarfaxOneOwner" BOOLEAN NOT NULL DEFAULT false,
    "flagAutocheckReport" BOOLEAN NOT NULL DEFAULT false,
    "flagAutocheckCert" BOOLEAN NOT NULL DEFAULT false,
    "flagAutocheckOne" BOOLEAN NOT NULL DEFAULT false,
    "purchasePrice" DECIMAL NOT NULL DEFAULT 0,
    "salePrice" DECIMAL NOT NULL DEFAULT 0,
    "regularPrice" DECIMAL,
    "cashPrice" DECIMAL,
    "wholesalePrice" DECIMAL,
    "loanValue" DECIMAL,
    "msrp" DECIMAL,
    "exportPrice" DECIMAL,
    "blueBook" DECIMAL,
    "blackBook" DECIMAL,
    "edmundsBook" DECIMAL,
    "nadaBook" DECIMAL,
    "downPayment" DECIMAL,
    "monthlyPayment" DECIMAL,
    "biWeeklyPayment" DECIMAL,
    "weeklyPayment" DECIMAL,
    "vehicleCost" DECIMAL,
    "repairCost" DECIMAL,
    "bottomLinePrice" DECIMAL,
    "preferredPriceText" TEXT,
    "salePriceExpires" DATETIME,
    "tax" DECIMAL NOT NULL DEFAULT 0,
    "total" DECIMAL NOT NULL DEFAULT 0,
    "balance" DECIMAL NOT NULL DEFAULT 0,
    "seoTitle" TEXT,
    "seoKeywords" TEXT,
    "seoDescription" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PURCHASED',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_Vehicle" ("balance", "bodyStyle", "cashPrice", "cityMpg", "color", "condition", "createdAt", "doors", "driveTrain", "engineCylinders", "engineSize", "financingAvailable", "fuelType", "guarantee", "highwayMpg", "interiorColor", "isCertified", "isFeatured", "isOneOwner", "keyId", "loanValue", "location", "make", "model", "msrp", "odometer", "purchasePrice", "regularPrice", "salePrice", "salesPerson", "seoDescription", "seoKeywords", "seoTitle", "status", "stockNumber", "tax", "titleStatus", "total", "transmissionSpeeds", "transmissionType", "trim", "updatedAt", "vin", "warrantyAvailable", "wholesalePrice", "year") SELECT "balance", "bodyStyle", "cashPrice", "cityMpg", "color", "condition", "createdAt", "doors", "driveTrain", "engineCylinders", "engineSize", "financingAvailable", "fuelType", "guarantee", "highwayMpg", "interiorColor", "isCertified", "isFeatured", "isOneOwner", "keyId", "loanValue", "location", "make", "model", "msrp", "odometer", "purchasePrice", "regularPrice", "salePrice", "salesPerson", "seoDescription", "seoKeywords", "seoTitle", "status", "stockNumber", "tax", "titleStatus", "total", "transmissionSpeeds", "transmissionType", "trim", "updatedAt", "vin", "warrantyAvailable", "wholesalePrice", "year" FROM "Vehicle";
DROP TABLE "Vehicle";
ALTER TABLE "new_Vehicle" RENAME TO "Vehicle";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
